[package]
name = "quizx"
default-run = "hidden_shift_stabrank"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }

[dependencies]
num = { workspace = true }
rustc-hash = "1.1.0"
rayon = "1.5.0"
ndarray = { version = "0.14.0", features = ["rayon"] }
approx = "0.4.0"
regex = "1.4.3"
rand = "0.8.3"
itertools = "0.10.1"
openqasm = "0.1.2"
thiserror = "1.0.57"
rstest = "0.18.2"
serde = { workspace = true }
serde_json = { workspace = true }
derive_more = "0.99.17"
portmatching = { git = "https://github.com/lmondada/portmatching.git", rev = "8adb23d9f", optional = true }

[features]
portmatching = ["dep:portmatching"]

[dev-dependencies]
rstest = "0.18.2"
